version: "3"

services:
  postgres:
    image: postgres:alpine
    # restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    # restart: always
    ports:
      - "6349:6349"

volumes:
  postgres-data:
