version: "3"

services:

  web:
    #build: 
      #context: .
      #dockerfile: docker/Dockerfile
    image: node:alpine
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    # belows settings overwrite default Dockerfile settings for local development. remove for actual deployment
    volumes:
      - .:/app
    working_dir: /app
    #command: 'npm run dev'
    command: 'tail -f /dev/null'

  postgres:
    image: postgres:alpine
    # restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes: 
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
